services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: local
      DEBUG: "true"
      LOG_JSON: "false"
      LOG_LEVEL: DEBUG
    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
